name: Build replay watcher

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up V version latest
      uses: vlang/setup-v@v1.1
      with:
        version: 'weekly.2022.30'
      id: v
    - name: Build replay_watcher.v -prod
      run: /opt/hostedtoolcache/v/0.3.0/x64/v -prod replay_watcher/replay_watcher.v
