name: Update README

on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run github
        env:
          URL: ${{ secrets.URL }}
          PORT: ${{ secrets.PORT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
